version: "3.8"

services:
  frontend:
    container_name: frontend
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: backend
    image: backend
    ports:
      - "8000:8000"
    restart: unless-stopped

